### ISSUE TITLE
The Default Domain is now working

### ISSUE THREAD

**Issue by mikelee1313** [rito2k/RDPs2RDG#2]
There is no parameter for Default Domain.  The RDG is using ".\account" when connecting to the guest machine.

I worked around the issue by hard coding the group properties.

    <group>
      <properties>
        <expanded>True</expanded>
        <name>$WorkspaceName</name>
      </properties>
      <logonCredentials inherit="None">
        <profileName scope="Local">Custom</profileName>
        <userName>sysadm</userName>
        <password />
        **<domain>contoso</domain>**
      </logonCredentials>
    </group>

There would need to be a "$DefaultDomain" parameter in your script that populates the domain setting in the Group section.

**Comment by rito2k** [comment]
Thanks for your feedback, feature request has been accepted and is already live in the master branch.
