### ISSUE TITLE
Server name field is populated with server name twice 

### ISSUE THREAD

**Issue by jamesmilford** [rito2k/RDPs2RDG#4]
Under the Server Settings tab of each server, the Server name field is populated with the server name twice with a space between each entry. This prevents a connection from being established. It also results in a "Spaces are not permitted in a server name" error when trying to save changes to the server's properties.

**Comment by rito2k** [comment]
HI @jamesmilford, I cannot repro the effect you are describing. Can you please provide a sanitized example (without real names or connection strings) for RDC files + the script call in the powershell command line?

**Comment by jamesmilford** [comment]
It appears the issue was related to duplicate entries created in the RDP files by MyWorkspace. A new release was pushed out yesterday and the issue is no longer reproducible.

**Comment by rito2k** [comment]
Ok, so from my understanding, the error was on the original RDP files, not on the script itself. I'll archive this issue then, because it does not apply. Thanks again for your testing!
